#%RAML 1.0
title: Yacao
version: 1.0
baseUri: https://ws.ls-sys.com/ws/yacao/api
baseUriParameters: {}
protocols:
- HTTPS
documentation:
- title: Yacao
  content: |
    # Introduction

    What does your API do?


    # Overview

    Things that the developers should know about


    # Authentication

    What is the preferred way of using the API?


    # Error Codes

    What errors and status codes can a user expect?


    # Rate limit

    Is there a limit to the number of requests an user can send?
types:
  ObtenercatálogodeCentros:
    example:
      value:
        centers:
        - id: <id del App>
          name: <nombre del Centro>
          diceros_id: <id del sistema Diceros>
    displayName: ObtenercatálogodeCentros
    type: object
    properties:
      centers:
        required: true
        displayName: centers
        type: array
        items:
          type: Center
  Center:
    example:
      value:
        id: <id del App>
        diceros_id: <id del sistema Diceros>
        name: Medina
    displayName: Center
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
      name:
        required: true
        displayName: name
        type: string
      diceros_id:
        required: true
        displayName: diceros_id
        type: string
  ObtenerCentroporID:
    example:
      value:
        id: <id del App>
        name: <Nombre del Centro>
        diceros_id: <id del sistema Diceros>
    displayName: ObtenerCentroporID
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
      name:
        required: true
        displayName: name
        type: string
      diceros_id:
        required: true
        displayName: diceros_id
        type: string
  ObtenercatálogodeRoles:
    example:
      value:
        roles:
        - id: <id del App>
          name: <nombre del rol>
          diceros_id: <id del sistema Diceros>
    displayName: ObtenercatálogodeRoles
    type: object
    properties:
      roles:
        required: true
        displayName: roles
        type: array
        items:
          type: Role
  Role:
    example:
      value:
        id: <id del App>
        diceros_id: <id del sistema Diceros>
        name: ADMINISTRADOR PARAMETROS
    displayName: Role
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
      name:
        required: true
        displayName: name
        type: string
      diceros_id:
        required: true
        displayName: diceros_id
        type: string
  ObtenerRolporID:
    example:
      value:
        id: <id del App>
        name: <nombre del rol>
        diceros_id: <id del sistema Diceros>
    displayName: ObtenerRolporID
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
      name:
        required: true
        displayName: name
        type: string
      diceros_id:
        required: true
        displayName: diceros_id
        type: string
  ObtenercatálogodeUsuarios:
    example:
      value:
        users:
        - id: <id del App>
          diceros_id: <id del sistema Diceros>
          name: <Nombre Completo del Usuario>
          email: ejemplo@yacao.com
          password: '****'
          center:
            id: <id del App>
            diceros_id: <id del sistema Diceros>
            name: Medina
          roles:
          - id: <id del App>
            diceros_id: <id del sistema Diceros>
            name: ADMINISTRADOR PARAMETROS
          active: true
    displayName: ObtenercatálogodeUsuarios
    type: object
    properties:
      users:
        required: true
        displayName: users
        type: array
        items:
          type: User
  User:
    displayName: User
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
      diceros_id:
        required: true
        displayName: diceros_id
        type: string
      name:
        required: true
        displayName: name
        type: string
      email:
        required: true
        displayName: email
        type: string
      password:
        required: true
        displayName: password
        type: string
      center:
        required: true
        displayName: center
        type: Center
      roles:
        required: true
        displayName: roles
        type: array
        items:
          type: Role
      active:
        required: true
        displayName: active
        type: string
  RegistrarnuevousuarioRequest:
    example:
      value:
        id: <id del App>
        diceros_id: <id del sistema Diceros>
        name: <Nombre Completo>
        email: ejemplpo@test.com
        password: 123654
        center:
          id: <id del App>
          diceros_id: <id del sistema Diceros>
          name: Medina
        roles:
        - id: <id del App>
          diceros_id: <id del sistema Diceros>
          name: Admin
        - id: <id del App>
          diceros_id: <id del sistema Diceros>
          name: Supervisor
        active: true
    displayName: RegistrarnuevousuarioRequest
    type: object
    properties:
      id:
        required: true
        displayName: id
        type: string
      diceros_id:
        required: true
        displayName: diceros_id
        type: string
      name:
        required: true
        displayName: name
        type: string
      email:
        required: true
        displayName: email
        type: string
      password:
        required: true
        displayName: password
        type: string
      center:
        required: true
        displayName: center
        type: Center
      roles:
        required: true
        displayName: roles
        type: array
        items:
          type: Role
      active:
        required: true
        displayName: active
        type: string
/parameter:
  /getCenterList.php:
    get:
      displayName: ObtenercatálogodeCentros
      description: Retorna el listado de las Agencias(Centros) registrados en el Sistema Diceros
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          description: Campo Obligatorio
          type: string
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  centers:
                  - id: <id del App>
                    name: <nombre del Centro>
                    diceros_id: <id del sistema Diceros>
              displayName: Obtener catálogo de Centros
              type: ObtenercatálogodeCentros
  /getCenter.php:
    get:
      displayName: ObtenerCentroporID
      description: Devuelbe los datos de una Agencia(centro) en especifico, por medio del su id
      queryParameters:
        id:
          required: true
          example:
            value: <id del App>
          displayName: id
          description: Campo Obligatorio
          type: string
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          type: string
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  id: <id del App>
                  name: <Nombre del Centro>
                  diceros_id: <id del sistema Diceros>
              displayName: Obtener Centro por ID
              type: ObtenerCentroporID
  /getRolList.php:
    get:
      displayName: ObtenercatálogodeRoles
      description: Retorna el listado de todos los roles que un usuario puede tener asignados.
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          description: Campo Obligatorio
          type: string
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  roles:
                  - id: <id del App>
                    name: <nombre del rol>
                    diceros_id: <id del sistema Diceros>
              displayName: Obtener catálogo de Roles
              type: ObtenercatálogodeRoles
  /getRol.php:
    get:
      displayName: ObtenerRolporID
      description: Devuelbe los datos de un rol en especifico.
      queryParameters:
        id:
          required: true
          example:
            value: <id del App>
          displayName: id
          type: string
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          description: Campo Obligatorio
          type: string
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  id: <id del App>
                  name: <nombre del rol>
                  diceros_id: <id del sistema Diceros>
              displayName: Obtener Rol por ID
              type: ObtenerRolporID
/user:
  /getUserList.php:
    get:
      displayName: ObtenercatálogodeUsuarios
      description: Obtiene el listado de todos los usuarios registrados en el Sistema Diceros
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          description: Campo Obligatorio
          type: string
      responses:
        200:
          description: Success
          body:
            application/json:
              example:
                value:
                  users:
                  - id: <id del App>
                    diceros_id: <id del sistema Diceros>
                    name: <Nombre Completo del Usuario>
                    email: ejemplo@yacao.com
                    password: '****'
                    center:
                      id: <id del App>
                      diceros_id: <id del sistema Diceros>
                      name: Medina
                    roles:
                    - id: <id del App>
                      diceros_id: <id del sistema Diceros>
                      name: ADMINISTRADOR PARAMETROS
                    active: true
              displayName: Obtener catálogo de Usuarios
              type: ObtenercatálogodeUsuarios
  /newUser.php:
    post:
      displayName: Registrarnuevousuario
      description: Registrar un nuevo usuario en el Sistema Diceros.
      body:
        application/json:
          example:
            value:
              id: <id del App>
              diceros_id: <id del sistema Diceros>
              name: <Nombre Completo>
              email: ejemplpo@test.com
              password: 123654
              center:
                id: <id del App>
                diceros_id: <id del sistema Diceros>
                name: Medina
              roles:
              - id: <id del App>
                diceros_id: <id del sistema Diceros>
                name: Admin
              - id: <id del App>
                diceros_id: <id del sistema Diceros>
                name: Supervisor
              active: true
          displayName: Body
          type: RegistrarnuevousuarioRequest
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          description: Campo Obligatorio
          type: string
        Content-Type:
          required: true
          example:
            value: application/json
          displayName: Content-Type
          description: Campo Obligatorio
          type: string
      responses:
        200:
          description: Success
/production:
  /newFarmVoucher.php:
    post:
      displayName: IngresodeRecibo(Recolecta)
      description: Registrar la recolecta de cacao en la finca
      body:
        text/plain:
          example:
            value: |
              {

                  "center":{

                      "id" : <id del App>,

                      "diceros_id" : <id del sistema Diceros>,

                      "name" : "Medina"

                  },

                  "supplier":{

                      "id" : <id del App>,

                      "diceros_id": <id del sistema Diceros>,

                      "name" : "suplidor 1 (Productor)",

                      "property":{

                          "id" : <id del App>,

                          "diceros_id": <id del sistema Diceros>,

                          "name" : "finca del suplidor 1"

                      }

                  },

                  "class_product":{

                      "id" : <id del App>,

                      "diceros_id" : <id del sistema Diceros>,

                      "name" : "Baba"

                  },

                  "series": "04",

                  "number": 1003,

                  "net_weight": 670,

                  "user":{

                      "id" : 1,

                      "diceros_id" : "<id del sistema Diceros>"

                  },

                  "crop":"2018-2019"

              }
          displayName: Body
          type: string
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          type: string
        Content-Type:
          required: true
          example:
            value: application/json
          displayName: Content-Type
          type: string
      responses:
        200:
          description: Success
  /unloadAndSorting.php:
    post:
      displayName: Descarga
      description: Registra la descarga de un recibo y lo clasifica
      body:
        text/plain:
          example:
            value: |
              {

                  "center":{

                      "id" : <id del App>,

                      "diceros_id": <id del sistema Diceros>,

                      "name": "Medina"

                  },

                  "voucher": {

                  	"diceros_id": <id del que retorna el proceso de Recolecta>,

                  	"id" : "04-123456"

                  },

                  "unload_weight": 5,

                  "process_type": 7,

                  "user":{

                      "id" : <id del App>,

                      "diceros_id" : "DAGUILA"

                  },

                  "sacona_number":109

              }
          displayName: Body
          type: string
      headers:
        Diceros-API-Key:
          required: true
          example:
            value: <API KEY>
          displayName: Diceros-API-Key
          type: string
        Content-Type:
          required: true
          example:
            value: application/json
          displayName: Content-Type
          type: string
      responses:
        200:
          description: Success
